package com.example.youyaoqilite.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.youyaoqilite.data.Cartoon;

import com.example.youyaoqilite.data.CartoonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartoonDaoConfig;

    private final CartoonDao cartoonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartoonDaoConfig = daoConfigMap.get(CartoonDao.class).clone();
        cartoonDaoConfig.initIdentityScope(type);

        cartoonDao = new CartoonDao(cartoonDaoConfig, this);

        registerDao(Cartoon.class, cartoonDao);
    }
    
    public void clear() {
        cartoonDaoConfig.clearIdentityScope();
    }

    public CartoonDao getCartoonDao() {
        return cartoonDao;
    }

}
